# Generated by Django 3.0 on 2021-04-22 15:41

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sight', '0002_comment_info_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-love_count', '-created_at'], 'verbose_name': '景点评论', 'verbose_name_plural': '景点评论'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': '景点详情', 'verbose_name_plural': '景点详情'},
        ),
        migrations.AlterModelOptions(
            name='sight',
            options={'ordering': ['-updated_at'], 'verbose_name': '景点信息', 'verbose_name_plural': '景点信息'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': '景点门票', 'verbose_name_plural': '景点门票'},
        ),
        migrations.AddField(
            model_name='comment',
            name='ip_address',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='IP地址'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_public',
            field=models.SmallIntegerField(default=1, verbose_name='是否公开'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_comment', to='sight.Comment', verbose_name='回复'),
        ),
        migrations.AlterField(
            model_name='info',
            name='entry_explain',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1024, null=True, verbose_name='入园参考'),
        ),
        migrations.AlterField(
            model_name='info',
            name='play_way',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='特色玩法'),
        ),
        migrations.AlterField(
            model_name='info',
            name='tips',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='温馨提示'),
        ),
        migrations.AlterField(
            model_name='info',
            name='traffic',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='交通到达'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='详细'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='remark',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='其他说明'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tips',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='预定须知'),
        ),
    ]
